spring.application.name=ai_service

server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/aiRecommendationFitness
spring.data.mongodb.database=aiRecommendationFitness

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
